Dev build and deploy failed due to below error (#114)
error: build error: building at STEP "RUN INLINE_RUNTIME_CHUNK=false npm run build": while running runtime: exit status 1
error: the build d1273d-tools/web-ecc-iosas-88 status is "Failed"
make: *** [Makefile:218: build-web] Error 1